CREATE DATABASE tutordb;
use tutordb;
CREATE TABLE users(
id BIGINT auto_increment PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
role VARCHAR(100) NOT NULL DEFAULT 'USER',
status VARCHAR(100) NOT NULL DEFAULT 'ACTIVE'
);
SELECT * FROM users;